name: Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::776069638114:role/github-oidc-paytrack-role
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: docker build -t paytrack .

      - name: Tag image
        run: |
          docker tag paytrack:latest \
          ${{ steps.login-ecr.outputs.registry }}/paytrack:latest

      - name: Push image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/paytrack:latest
